// Generates src/theme.css, the Skeleton v5 theme for Gary.
// Run: node scripts/theme-scales.mjs
// Edit the ramps below, rerun, commit the CSS. Do not hand-edit theme.css.

import { writeFileSync } from "node:fs";

// Lightness ramp shared by chromatic scales, 50 -> 950.
const STEPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
const L_CHROMA = [0.97, 0.93, 0.87, 0.79, 0.71, 0.63, 0.55, 0.47, 0.39, 0.31, 0.24];
// Surface ramp is stretched at the dark end: the app lives in 800-950.
const L_SURFACE = [0.985, 0.955, 0.91, 0.84, 0.72, 0.58, 0.45, 0.35, 0.27, 0.215, 0.165];
// Chroma envelope for chromatic scales, peaks around 400-500.
const C_ENV = [0.03, 0.06, 0.09, 0.12, 0.15, 0.16, 0.15, 0.13, 0.11, 0.09, 0.07];

// hue: oklch hue. chroma: multiplier on C_ENV. Surface uses its own flat chroma.
const SCALES = {
    surface: { hue: 258, chroma: 0.018, flat: true, L: L_SURFACE },
    primary: { hue: 235, chroma: 0.95 },   // sky, the accent
    secondary: { hue: 295, chroma: 1.0 },  // purple, the model/actor
    tertiary: { hue: 190, chroma: 0.85 },  // teal, unused today
    success: { hue: 162, chroma: 0.9 },    // emerald
    warning: { hue: 72, chroma: 1.0 },     // amber
    error: { hue: 24, chroma: 1.0 },       // red
};

const fmt = (n) => Number(n.toFixed(3)).toString();
const lines = [];
for (const [name, s] of Object.entries(SCALES)) {
    const L = s.L ?? L_CHROMA;
    STEPS.forEach((step, i) => {
        const c = s.flat ? s.chroma : C_ENV[i] * s.chroma;
        lines.push(`\t--color-${name}-${step}: oklch(${fmt(L[i])} ${fmt(c)} ${s.hue});`);
    });
    lines.push(`\t--color-${name}-contrast-dark: var(--color-${name}-950);`);
    lines.push(`\t--color-${name}-contrast-light: var(--color-${name}-50);`);
    STEPS.forEach((step) => {
        const side = step <= 300 ? "dark" : "light";
        lines.push(`\t--color-${name}-contrast-${step}: var(--color-${name}-contrast-${side});`);
    });
    lines.push("");
}

const css = `/* Generated by scripts/theme-scales.mjs. Edit the script, not this file. */
/* Skeleton v5 theme. Color scales below; semantic tokens live in global.css. */

[data-theme='gary'] {
\t--spacing: 0.25rem;
\t--text-scaling: 1;
\t--radius-base: 0.375rem;
\t--radius-container: 0.625rem;
\t--default-border-width: 1px;
\t--default-outline-width: 1px;
\t--default-ring-width: 1px;
\t--corner-shape-base: inherit;
\t--corner-shape-container: inherit;

\t--typo-base--font-family: var(--font-sans);
\t--typo-base--font-size: inherit;
\t--typo-base--color-light: var(--color-surface-950);
\t--typo-base--color-dark: var(--color-surface-50);
\t--typo-base--line-height: inherit;
\t--typo-base--font-weight: normal;
\t--typo-base--font-style: normal;
\t--typo-base--letter-spacing: 0em;
\t--typo-heading--font-family: inherit;
\t--typo-heading--color-light: inherit;
\t--typo-heading--color-dark: inherit;
\t--typo-heading--font-weight: 600;
\t--typo-heading--font-style: normal;
\t--typo-heading--letter-spacing: inherit;
\t--typo-anchor--font-family: inherit;
\t--typo-anchor--font-size: inherit;
\t--typo-anchor--color-light: var(--color-primary-600);
\t--typo-anchor--color-dark: var(--color-primary-400);
\t--typo-anchor--line-height: inherit;
\t--typo-anchor--font-weight: inherit;

\t--color-root-bg-light: var(--color-surface-100);
\t--color-root-bg-dark: var(--color-surface-950);
\t--color-brand-light: var(--color-primary-600);
\t--color-brand-contrast-light: var(--color-primary-contrast-600);
\t--color-brand-dark: var(--color-primary-400);
\t--color-brand-contrast-dark: var(--color-primary-contrast-400);

${lines.join("\n")}}
`;
writeFileSync(new URL("../src/theme.css", import.meta.url), css);
console.log("wrote src/theme.css");
